
device: ${core.device}

cache_dir: ${core.cache_dir}

hyperparams:
  instruct:
    guidance_scale: 7.5
    image_guidance_scale: 1.5

defaults:
  - sd: stable_diffusion
  - inpainting: stable_inpainting
  - instruct: instruct_pix_2_pix
  - zero: zero123plus