core:
  dtype: 
    _target_: src.utils.utils.getTorchType
    string: float16
  cache_dir: cache
    
  device: cuda

misc:
  load_image_path: "/home/andrea/Scaricati/mushroom.png"
  prompt: 'A statue of a man with a sword behind'
  edit: 'make it made of gold'
  seed: 41

out_path: 'out/'
output:
  generate: ${out_path}sd.png
  zero: ${out_path}zero.png
  zero_edited: ${out_path}zero_edited.png
  edit: ${out_path}p2p.png

defaults:
  - models: default